name: PlayerTrolls
version: ${project.version}
main: dev.benergy10.playertrolls.PlayerTrolls
api-version: 1.13
authors: [ benwo1110 ]
description: ${project.description}
softdepend: [ ProtocolLib, LibsDisguises ]
